name: remote ssh command
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Update on server
    runs-on: ubuntu-latest
    steps:
      - name: Connecting to remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          # host: ${{ secrets.HOST }}
          # username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.PORT }}
          host: 142.93.242.42
          username: root
          password: HaCkErB0y
          port: 22
          script: |
            if [ -d /home/front_stage/ ]; then
              cd /home/front_stage/
              git pull
            else
              git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} /home/front_stage/
              cd /home/front_stage/
            fi
            if [-d .node_modules/]; then
              rm -rf .node_modules/
            fi
            npm install

            touch action_test.txt
            echo "test worked" > action_test.txt
